MyBox:

<MyBox>:
    orientation: "vertical"
    BoxLayout:
        orientation:"horizontal"
        size_hint_y: 0.20
        Label:
            id: score
            text: "Score: " #to insert f-string
        Label:
            id: time
            text: "Time: " #to insert f-string
    Widget:
        id: hangman_image
    Label:
        id: game_word
        font_size: "50dp"
    MyLetterGrid:

<MyLetterGrid>:



